[package]
name = "sowm-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
interprocess = "2.2.2"
users = "0.11.0"

sowm-common = { path = "../sowm-common/" }
clap = { version = "4.5.26", features = ["derive"] }
